---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-odcs-compose
spec:
  params:
    - name: IMAGE
      type: string
      description: The image to use for this task
      default: ""
  workspaces:
    - name: workdir
      description: |
        Working directory that will be used for reading configuration files
        and writing the output
  results:
    - name: repodir_path
      description: Directory to write the result .repo files.
  steps:
    - name: generate-odcs-compose
      image: "$(params.IMAGE)"
      script: |
        #!/bin/bash
        set -ex

        repodir_path="$(workspaces.workdir.path)/repos"
        cd "$(workspaces.workdir.path)"

        odcs_compose_generator.py \
          --compose-file-path \
          "${repodir_path}/repofile.repo" \
          --container-yml-path \
          container.yaml \
          --content-sets-yaml-path \
          content_sets.yml

        echo "$repodir_path" > $(results.repodir_path.path)
