---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-odcs-compose
spec:
  params:
    - name: COMPOSE_INPUTS
      description: relative path from workdir workspace to the compose inputs file
      default: source/compose_inputs.yaml
    - name: COMPOSE_OUTPUTS
      description: relative path from workdir workspace to store compose output files
      default: fetched.repos.d
  workspaces:
    - name: workdir
      description: |
        Working directory that will be used for reading configuration files
        and writing the output
  results:
    - name: repodir_path
      description: Directory to write the result .repo files.
  steps:
    - name: generate-odcs-compose
      image: quay.io/redhat-appstudio/tools@sha256:5c76e040c18e8d8b1cb608c7fe1bca2bd3c8cb9adfd790388589761660ccadf8
      env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: odcs-service-account
              key: client-id
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: odcs-service-account
              key: client-secret
        - name: COMPOSE_INPUTS
          value: "$(params.COMPOSE_INPUTS)"
        - name: COMPOSE_OUTPUTS
          value: "$(params.COMPOSE_OUTPUTS)"
      script: |
        #!/bin/bash
        set -ex

        repodir_path="$(workspaces.workdir.path)/${COMPOSE_OUTPUTS}"

        cd "$(workspaces.workdir.path)"

        odcs_compose_generator \
          --compose-input-yaml-path "${COMPOSE_INPUTS}" \
          --compose-dir-path "${repodir_path}"

        echo "$repodir_path" > $(results.repodir_path.path)
