apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/redhat-appstudio/tekton-tools?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[pull_request]'
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
    pipelinesascode.tekton.dev/task: tasks/verify-signed-rpms/0.1/verify-signed-rpms.yaml
  labels:
    appstudio.openshift.io/application: tekton-tools
    appstudio.openshift.io/component: tekton-tools
    pipelines.appstudio.openshift.io/type: build
  name: verify-signed-rpms-pull-request
  namespace: gbenhaim-tenant
spec:
  pipelineSpec:
    params:
    - name: IMAGE
      type: string
      description: The image to use for this pipeline
      default: quay.io/redhat-user-workloads/rhtap-o11y-tenant/tools/tools:6eea7e09df3e96d770117e5bc71e7a05191cf012
    - name: INPUT 
      type: string
      default: |
        {
          "components": [
              {
                  "containerImage": "quay.io/o11y_tests/unsigned-rpms:latest"
              },
              {
                  "containerImage": "quay.io/o11y_tests/signed-rpms:latest"
              },
              {
                  "containerImage": "quay.io/o11y_tests/error:latest"
              }             
          ]
        }
    - name: FAIL_UNSIGNED
      type: string
      default: False
    tasks:
      - name: verify-signed-rpms
        params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: INPUT
          value: $(params.INPUT)
        - name: FAIL_UNSIGNED
          value: $(params.FAIL_UNSIGNED)
        taskRef:
          name: verify-signed-rpms
          kind: Task
      - name: verify-output
        runAfter:
          - verify-signed-rpms
        params:
          - name: IMAGE
            value: $(params.IMAGE)
          - name: verify-signed-rpms-output
            value: $(tasks.verify-signed-rpms.results.verification-output)
        taskSpec:
          params:
            - name: IMAGE
              type: string
              description: The image to use for this task
              default: ""
            - name: verify-signed-rpms-output
              type: string
          steps:
            - name: verify-output
              image: "$(params.IMAGE)"
              script: |
                #!/bin/bash
                set -e
              
                output="$(params.verify-signed-rpms-output)"
                echo "Output: $output"

                if [[ "$output" == *"quay.io/o11y_tests/unsigned-rpms:latest: ansible-automation-platform-common-2.4-1.el8ap, python39-six-1.16.0-2.el8pc"* ]] && 
                   [[ "$output" == *"error: image "quay.io/o11y_tests/error:latest" not found: manifest unknown: manifest unknown"* ]] && 
                   [[ "$output" != *"quay.io/o11y_tests/signed-rpms:latest"* ]]; then 
                  echo "Output matches!"
                else
                  echo "Output does not match"
                  exit 1
                fi
