apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/redhat-appstudio/tekton-tools?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[pull_request]'
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
    pipelinesascode.tekton.dev/task: tasks/verify-signed-rpms/0.1/verify-signed-rpms.yaml
  labels:
    appstudio.openshift.io/application: tekton-tools
    appstudio.openshift.io/component: tekton-tools
    pipelines.appstudio.openshift.io/type: build
  name: verify-signed-rpms-pull-request
  namespace: gbenhaim-tenant
spec:
  pipelineSpec:
    params:
    - name: IMAGE
      type: string
      description: The image to use for this pipeline
      default: quay.io/redhat-user-workloads/rhtap-o11y-tenant/tools/tools:1126d8b701fe1448fe77e98f1906fd685fdbe3d4
    - name: FAIL_UNSIGNED
      type: string
      default: False
    tasks:
      - name: verify-signed-rpms-error
        params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: INPUT
          value: |
            {
              "components": [
                  {
                      "containerImage": "quay.io/o11y_tests/unsigned-rpms:latest"
                  },
                  {
                      "containerImage": "quay.io/o11y_tests/signed-rpms:latest"
                  },
                  {
                      "containerImage": "quay.io/o11y_tests/error:latest"
                  }             
              ]
            }
        - name: FAIL_UNSIGNED
          value: $(params.FAIL_UNSIGNED)
        taskRef:
          name: verify-signed-rpms
          kind: Task
      - name: verify-output-error
        runAfter:
          - verify-signed-rpms-error
        params:
          - name: IMAGE
            value: $(params.IMAGE)
          - name: TEST_OUTPUT
            value: $(tasks.verify-signed-rpms-error.results.TEST_OUTPUT)
        taskSpec:
          params:
            - name: IMAGE
              type: string
              description: The image to use for this task
              default: ""
            - name: TEST_OUTPUT
              type: string
              description: output of the task
          steps:
            - name: verify-output
              image: "$(params.IMAGE)"
              script: |
                #!/bin/bash
                set -ex
              
                output=$(params.TEST_OUTPUT)
                echo "Output: $output"

                if [[ "$output" == *"completed: Not all RPMs were confirmed to be signed. Refer to Tekton task output for details"* ]] && 
                   [[ "$output" == *"ERROR"* ]]; then 
                  echo "Output matches!"
                else
                  echo "Output does not match"
                  exit 1
                fi
      - name: verify-signed-rpms-success
        params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: INPUT
          value: |
            {
              "components": [
                  {
                      "containerImage": "quay.io/o11y_tests/signed-rpms:latest"
                  }            
              ]
            }
        - name: FAIL_UNSIGNED
          value: $(params.FAIL_UNSIGNED)
        taskRef:
          name: verify-signed-rpms
          kind: Task
      - name: verify-output-success
        runAfter:
          - verify-signed-rpms-success
        params:
          - name: IMAGE
            value: $(params.IMAGE)
          - name: TEST_OUTPUT
            value: $(tasks.verify-signed-rpms-success.results.TEST_OUTPUT)
        taskSpec:
          params:
            - name: IMAGE
              type: string
              description: The image to use for this task
              default: ""
            - name: TEST_OUTPUT
              type: string
              description: output of the task
          steps:
            - name: verify-output
              image: "$(params.IMAGE)"
              script: |
                #!/bin/bash
                set -ex
              
                output=$(params.TEST_OUTPUT)
                echo "Output: $output"

                if [[ "$output" == *"completed: No unsigned RPMs"* ]] && 
                   [[ "$output" == *"SUCCESS"* ]]; then 
                  echo "Output matches!"
                else
                  echo "Output does not match"
                  exit 1
                fi
